version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: default_db
      MYSQL_USER: user_blog
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api-gateway:
    build:
      context: ./dotnet-angular-blog
      dockerfile: dockerfile.api-gateway
    environment:
      # - ConnectionStrings__BlogDbConnection="server=dbsigma.mysql.database.azure.com;port=3306;user=sigma;password=SAAJNfounders.@)22;database=default_db;sslmode=Required"
      - ConnectionStrings__BlogDbConnection="server=db;port=3306;user=root;password=pass;database=default_db"
      - JWT__ValidAudience="http://localhost:4200"
      - JWT__ValidIssuer="http://localhost:5000"
      - JWT__Secret="JWTAuthenticationHIGHsecuredPasswordVVVp1OH7Xzyr"
      # - Kestrel__Endpoints__Https__Url="https://localhost:7257"
      - Kestrel__Endpoints__Http__Url="http://localhost:7257"
      - Kestrel__Endpoints__Https__Url="https://localhost:7258"
      - Kestrel__Endpoints__Https__Certificate__Path="./Certificates/cert.pem"
    ports:
      - "7257:7257"
    depends_on:
      - db

  api-upload:
    build:
      context: ./image-upload
      dockerfile: dockerfile.api-upload
    environment:
      - AzureBlobStorageConnectionString="UseDevelopmentStorage=true"
    ports:
      - "8002:8002"
    depends_on:
      - db

  app-node:
    build:
      context: ./ClientApp
      dockerfile: dockerfile.app-node
    ports:
      - "4200:4200"
    depends_on:
      - db

volumes:
  db_data:
